services:
  automation:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./reports:/framework/reports
      - ./test-results:/framework/test-results
    command:
      [
        "python",
        "-m",
        "pytest",
        "-m",
        "smoke or api",
        "--browser",
        "chromium",
        "-v"
      ]